"""initial schema

Revision ID: 16422bed4551
Revises: 
Create Date: 2026-08-12 05:36:20.606252
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '16422bed4551'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('time_spent_s', sa.Integer(), nullable=False),
    sa.Column('goal_met', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.String(length=8), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('pt', sa.Text(), nullable=False),
    sa.Column('pl', sa.Text(), nullable=False),
    sa.Column('pl_alt', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pt_alt', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('variant', sa.String(length=8), nullable=False),
    sa.Column('part_of_speech', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('article', sa.String(length=8), nullable=True),
    sa.Column('plural', sa.Text(), nullable=True),
    sa.Column('ipa', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pt', 'pl', name='uq_items_pt_pl')
    )
    op.create_index(op.f('ix_items_cefr_level'), 'items', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_items_part_of_speech'), 'items', ['part_of_speech'], unique=False)
    op.create_index(op.f('ix_items_verified'), 'items', ['verified'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('deck_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('new_per_day', sa.Integer(), nullable=False),
    sa.Column('review_limit', sa.Integer(), nullable=False),
    sa.Column('desired_retention', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('enabled_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tts_voice', sa.String(length=64), nullable=False),
    sa.Column('tts_speed', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('autoplay_audio', sa.Boolean(), nullable=False),
    sa.Column('accent_strict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('deck_items',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deck_id', 'item_id')
    )
    op.create_table('examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('pt', sa.Text(), nullable=False),
    sa.Column('pl', sa.Text(), nullable=False),
    sa.Column('cloze_start', sa.Integer(), nullable=True),
    sa.Column('cloze_end', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_item_id'), 'examples', ['item_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('question_index', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_index', name='uq_reviews_session_question')
    )
    op.create_index('ix_reviews_user_time', 'reviews', ['user_id', 'reviewed_at'], unique=False)
    op.create_table('user_item_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('correct_reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', 'direction')
    )
    op.create_index('ix_user_item_state_due', 'user_item_state', ['user_id', 'due'], unique=False)
    op.create_index('ix_user_item_state_user_item', 'user_item_state', ['user_id', 'item_id'], unique=False)
    # ### end Alembic commands ###

    # Dictionary search runs LIKE '%needle%' over both languages. A trigram GIN
    # index makes that fast; if the extension is not available the search still
    # works, just with a sequential scan, so this must not fail the migration.
    op.execute(
        """
        DO $$
        BEGIN
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE INDEX IF NOT EXISTS ix_items_pt_trgm ON items USING gin (lower(pt) gin_trgm_ops);
            CREATE INDEX IF NOT EXISTS ix_items_pl_trgm ON items USING gin (lower(pl) gin_trgm_ops);
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'pg_trgm unavailable, skipping trigram indexes';
        END $$;
        """
    )


def downgrade() -> None:
    op.execute('DROP INDEX IF EXISTS ix_items_pl_trgm')
    op.execute('DROP INDEX IF EXISTS ix_items_pt_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_item_state_user_item', table_name='user_item_state')
    op.drop_index('ix_user_item_state_due', table_name='user_item_state')
    op.drop_table('user_item_state')
    op.drop_index('ix_reviews_user_time', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_examples_item_id'), table_name='examples')
    op.drop_table('examples')
    op.drop_table('deck_items')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_items_verified'), table_name='items')
    op.drop_index(op.f('ix_items_part_of_speech'), table_name='items')
    op.drop_index(op.f('ix_items_cefr_level'), table_name='items')
    op.drop_table('items')
    op.drop_table('decks')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
